"""add enterprise_plan

Revision ID: 7385cc9f3b92
Revises: 16deccb96d2a
Create Date: 2026-07-30 15:17:50.979136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7385cc9f3b92'
down_revision: Union[str, Sequence[str], None] = '16deccb96d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('compititors', 'compititors_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('pricing_data', sa.Column('enterprise_plan', sa.Boolean(), nullable=False))
    op.drop_column('pricing_data', 'starter_plan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_data', sa.Column('starter_plan', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('pricing_data', 'enterprise_plan')
    op.alter_column('compititors', 'compititors_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
