"""Added Relation Between Companies to BattleCard and ResearchRun

Revision ID: cfcd345bcf4a
Revises: 7385cc9f3b92
Create Date: 2026-08-08 15:00:43.963453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcd345bcf4a'
down_revision: Union[str, Sequence[str], None] = '7385cc9f3b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
